# Splunk SentinelOps App configuration file

[install]
is_configured = 0

[ui]
is_visible = 1
label = Splunk SentinelOps AI

[launcher]
author = shoaibharoon10
description = Splunk SentinelOps AI Agentic SOC Triage investigation assistant tools mapping configurations.
version = 0.1.0

[package]
id = SplunkSentinelOps
check_for_updates = 0
